version: '3.1'

services:
  db:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
  
  api:
    image: challenge:latest
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ".env"

